on:
  schedule:
    # runs every day at 7:00 AM UTC = 3AM ET
    - cron:  '0 7 * * *'
  workflow_dispatch:

name: update_otc

jobs:
  update:
    name: update data
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            nflverse/nflverse-data
            nflverse/nflreadr
            ropensci/piggyback
            local::.
            any::arrow
            any::qs
      - name: Run otc update script
        run: Rscript data-raw/release_otc_player_ids.R
